routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('landing');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::put('users/verify/{Id}','UserController@verify')->name('users.verify');
Route::resource('users', 'UserController');

Route::post('search','SearchController@search')->name('search');
Route::get('search','BookController@index')->name('search.index');

Route::get('books/createBook','BookController@createBook')->name('books.createBook');
Route::post('books/createBook','BookController@storeBook')->name('books.storeBook');
Route::resource('books', 'BookController');

Route::resource('authors', 'AuthorController');


Route::resource('bookList', 'BookListController');

Route::resource('bookIssueLog','BookIssueLogController');
//Route::resource('books', 'BookController');


/*
 * uzytkownicy:
 *
 * dodawanie ksiazek
    * dodawanie egzemplazy
 * wypozyczanie ksiazek
    * zatwierdzanie ksiazek

*/

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\bookIssue;
use Laravel\Scout\Searchable;
use Illuminate\Database\Eloquent\SoftDeletes;

class Book extends Model
{
    use Searchable,SoftDeletes;
    protected $dates = ['deleted_at'];
    protected $guarded = ['id'];
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token','created_at','updated_at','authorId'
    ];
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'authorId', 'title', 'desc', 'releaseDate','genre'
    ];
    protected $appends = ['avaliable_count'];

    protected static function boot() {
        parent::boot();

        static::deleting(function($book) { // before delete() method call this
            $book->issue()->delete();
        });
    }



    public function author() {
        return $this->hasOne('App\Models\Author','id','authorId');
    }
    public function issue() {
        return $this->hasMany('App\bookIssue','bookId','id');
    }
    public function avaliableCount(){
        $c = bookIssue::where('bookId',$this->id)->where('avaliable',1)->count();
        return $c;
    }
    private $freeIssue=null;
    public function freeIssue(){
        if($this->freeIssue)
            return $this->freeIssue;
        $this->freeIssue = bookIssue::where('bookId',$this->id)->where('avaliable',1)->first();
        return $this->freeIssue;
    }
    public function getAvaliableCountAttribute($value)
    {
        return $this->avaliableCount();
    }
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\bookIssue;
use App\Models\Book;
use App\Models\Author;
class BookController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'isAdmin']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $books = Book::with('issue')->with('author')->paginate(15);

        return view('books.index')->with('books', $books);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $books = Book::all();
        return view('books.add', ['books'=>$books]);
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->validate($request, [
            'bookId'=>'required|exists:books,id',
            'count'=>'required|integer|min:1|max:100',
        ]);

        $newBooksCount = (int)$request['count'];
        for ($i=0;$i<$newBooksCount;$i++){
            bookIssue::create($request->only('bookId'));
        }
        $message = $newBooksCount>1 ? 'Ksiazki dodane pomyślnie':'Ksiazka dodana pomyślnie';
        return redirect()->route('books.index')
            ->with('flash_message', $message);
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $book = Book::findOrFail($id);
        $book->delete();

        return redirect()->route('books.index')
            ->with('flash_message',
                'Ksiazka usunieta pomyślnie.');
    }


    public function createBook(){
        $authors = Author::all();
        return view('books.create',['authors'=>$authors]);
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function storeBook(Request $request)
    {
        $this->validate($request, [
            'title'=>'required|max:120',
            'authorId'=>'required|exists:authors,id',
            'desc'=>'required|max:1024',
            'releaseDate'=>'required|date',
            'genre'=>'required|string|max:50'
        ]);
        Book::create($request->only(['title','authorId','desc','releaseDate','genre']));

        return redirect()->route('books.index')
            ->with('flash_message', 'Ksiazka dodana pomyślnie');
    }
}

resources/views/books/add.blade.php
@extends('layouts.app')

@section('title', '| Dodaj uzytkownika')

@section('content')



     <div class="container">

        {{ Form::open(array('url' => 'books')) }}

        <div class="form-group">
            {{ Form::label('book', 'Książka') }}
            <select name="bookId">
                <option value="">Wybierz ksiazke...</option>
                @foreach($books as $book)
                    <option value="{{$book->id}}">{{$book->title}}</option>
                @endforeach
            </select>
        </div>
        <div class="form-group">
            {{ Form::label('count', 'Ilosc nowych egzemplazy') }}
            {{ Form::number('count', '1') }}
        </div><br/>
        {{ Form::submit('Dodaj', array('class' => 'btn btn-primary')) }}

        {{ Form::close() }}
     </div>
    </div>

@endsection

resources/views/books/create.blade.php
@extends('layouts.app')

@section('title', '| Dodaj ksiazke')

@section('content')

    <div class='container'>




        {{ Form::open(array('url' => route('books.storeBook'))) }}

        <div class="form-group">
            {{ Form::label('title', 'tytuł') }}
            {{ Form::text('title', '', array('class' => 'form-control')) }}
        </div>

        <div class="form-group">
            {{ Form::label('book', 'Autor') }}
            <select name="authorId">
                <option value="">Wybierz autora...</option>
                @foreach($authors as $author)
                    <option value="{{$author->id}}">{{$author->name}}</option>
                @endforeach
            </select>
            <a href="{{ route('authors.create') }}" class="btn btn-success">Dodaj nowego autora</a>

        </div>
        <div class="form-group">
            {{ Form::label('desc', 'opis') }}
            {{ Form::textarea('desc', '', array('class' => 'form-control')) }}
        </div>
        <div class="form-group">
            {{ Form::label('genre', 'gatunek') }}
            {{ Form::textarea('genre', '', array('class' => 'form-control')) }}
        </div>
        <div class="form-group">
            {{ Form::label('releaseDate', 'Data wydania') }}
            {{ Form::date('releaseDate', '', array('class' => 'form-control')) }}
        </div><br/>
        {{ Form::submit('Dodaj', array('class' => 'btn btn-primary')) }}

        {{ Form::close() }}

    </div>

@endsection

resources/views/books/index.blade.php
@extends('layouts.app')

@section('title', '| Uzytkownicy')

@section('content')

    <div class="container">
        {{ Form::open(array('url' => 'search')) }}
        @include('search.search')

        {{ Form::close() }}
        <hr>

            <table id="t_test"  class="table table-bordered table-striped">

                <thead>
                <tr>
                    <th>Id</th>
                    <th>Ksiazka</th>
                    <th>Ilosc</th>
                    <th>dostępne</th>
                    <th>gatunek</th>
                    <th>Data dodania</th>
                    <th>Operacje</th>
                </tr>
                </thead>

                <tbody>
                @foreach ($books as $book)
                    <tr>

                        <td>{{ $book->id }}</td>
                        <td>{{ $book->title }}</td>
                        <td>{{ count($book->issue) }}</td>
                        <td>{{ $book->avaliableCount() }}</td>
                        <td>{{ $book->genre }}</td>
                        <td>{{ $book->created_at }}</td>

                        {{--<td>{{ $bookIssue->avaliable ? "Tak":"Nie" }}</td>
                        <td>{{ $bookIssue->created_at }}</td>
--}}
                        <td>
                            {!! Form::open(['method' => 'DELETE', 'route' => ['books.destroy', $book->id] ]) !!}
                                {!! Form::submit('Usuń', ['class' => 'btn btn-danger']) !!}
                            {!! Form::close() !!}

                        </td>
                    </tr>
                @endforeach
                </tbody>

            </table>


        <a href="{{ route('books.create') }}" class="btn btn-success">Dodaj egzemplaż</a>
        <a href="{{ route('books.createBook') }}" class="btn btn-success">Dodaj nową książke</a>
        {!! $searchAd or '' !!}
        {{$books->links()}}

    </div>

@endsection